-- table query
select b.title book, c.title course, l.dateL loanDate, g.name grade, p.name publisher, s.name school, r.name room, t.name teacher from book b, course c, loan l, grade g, publisher p, school s, room r, teacher t, teachers_room tr, teacher_level_course tlc where p.publisher_id = b.pid and b.book_id = l.bid and s.school_id = t.sid and r.room_id = tr.rid and t.teacher_id = tr.tid and tlc.teacher_level_course_id = l.tlcid and t.teacher_id = tlc.tid and g.grade_id = tlc.gid and c.course_id = tlc.cid order by l.loan_id, s.school_id, t.teacher_id, c.course_id, r.room_id, b.book_id;

-- Task 1: Obtain for each of the schools, the number of books that have been loaned to each publishers.
select p.name publisher, s.name school, count(*) "total amount of books" from book b, course c, loan l, grade g, publisher p, school s, room r, teacher t, teachers_room tr, teacher_level_course tlc where
 b.book_id = l.bid and c.course_id = tlc.cid and g.grade_id = tlc.gid and p.publisher_id = b.pid and s.school_id = t.sid and r.room_id = tr.rid and t.teacher_id = tr.tid and tlc.teacher_level_course_id = l.tlcid and t.teacher_id = tlc.tid group by s.school_id, p.publisher_id;

-- Ex 2: For each school, find the book that has been on loan the longest and the teacher in charge of it
select sx.name school, lx.dateL "Loan date", bx.title "Book w longest loan", tx.name "teacher who hold the book longest" from  book bx, course cx,loan lx, grade gx, publisher px, school sx, room rx, teacher tx, teacher_level_course tlcx, teachers_room trx where px.publisher_id = bx.pid and bx.book_id = lx.bid and sx.school_id = tx.sid and rx.room_id = trx.rid and tx.teacher_id = trx.tid and tlcx.teacher_level_course_id = lx.tlcid and tx.teacher_id = tlcx.tid and gx.grade_id = tlcx.gid and cx.course_id = tlcx.cid and lx.dateL <= all( select ly.dateL from book by, course cy, grade gy, loan ly, publisher py, school sy, room ry, teacher ty, teachers_room try, teacher_level_course tlcy  where py.publisher_id = by.pid and by.book_id = ly.bid and sy.school_id = ty.sid and ry.room_id = try.rid and ty.teacher_id = try.tid and tlcy.teacher_level_course_id = ly.tlcid and ty.teacher_id = tlcy.tid and gy.grade_id = tlcy.gid and cx.course_id = tlcy.cid and sy.school_id = sy.school_id);
